### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by llayerlinux** [Beseting/NesEmulator#4]
All permissions succesfull granted, but it is not work (Android 13)

meow new tls: 0xb400007aaaf2e0a0
2024-04-14 08:19:47.733 18719-18745 libMEOW                 com.ym.nesemulator                   D  meow reload base cfg path: na
2024-04-14 08:19:47.733 18719-18745 libMEOW                 com.ym.nesemulator                   D  meow reload overlay cfg path: na
2024-04-14 08:19:47.733 18719-18745 QT                      com.ym.nesemulator                   W  qt_process_init() called
2024-04-14 08:19:47.733 18719-18745 QT                      com.ym.nesemulator                   E  [QT]file does not exist
2024-04-14 08:19:47.733 18719-18745 QT                      com.ym.nesemulator                   W  Support!!
2024-04-14 08:19:47.734 18719-18745 libMEOW_gift            com.ym.nesemulator                   I  open /data/performance/gift/arc.ini
2024-04-14 08:19:47.734 18719-18745 QT                      com.ym.nesemulator                   E  [QT]file does not exist
 D  hardware acceleration = true, forceHwAccelerated = false
2024-04-14 08:19:47.762 18719-18719 libMEOW                 com.ym.nesemulator                   D  meow new tls: 0xb400007aaaf1e090
2024-04-14 08:19:47.762 18719-18719 libMEOW                 com.ym.nesemulator                   D  applied 1 plugins for [com.ym.nesemulator]:
2024-04-14 08:19:47.762 18719-18719 libMEOW                 com.ym.nesemulator                   D    plugin 1: [libMEOW_gift.so]: 0xb400007a6aea1820
2024-04-14 08:19:47.762 18719-18719 libMEOW                 com.ym.nesemulator                   D  rebuild call chain: 0xb400007aaaf3e0b0
2024-04-14 08:19:47.763 18719-18719 InputTransport          com.ym.nesemulator                   D  Create ARC handle: 0xb4000078caef5770
2024-04-14 08:19:47.764  1410-1410  ActivityTaskManager     system_server                        E  [LUCID] lucid_r.packageNamge: com.ym.nesemulator lucid_r.state:PAUSING ignored!
endAllActiveAnimators on 0xb4000079baeeb0c0 (RippleDrawable) with handle 0xb4000078caee0440

**Comment by Litesav-L** [comment]
E  java.lang.NullPointerException: Attempt to invoke virtual method 'void a.g$c.a()' on a null object reference
                                                                                                    	at a.g.e(Unknown Source:31)
                                                                                                    	at com.ym.library.base.BaseEmulatorActivity.a(Unknown Source:11)
                                                                                                    	at com.ym.library.base.c.c(Unknown Source:295)
                                                                                                    	at com.ym.library.base.BaseEmulatorActivity.a(Unknown Source:2)
                                                                                                    	at c.d$d.a(Unknown Source:6)
                                                                                                    	at com.ym.library.ui.multitouchbutton.MultitouchImageButton.a(Unknown Source:8)

**Comment by llayerlinux** [comment]
E  java.lang.NullPointerException: Attempt to invoke virtual method 'void a.g$c.a()' on a null object reference
                                                                                                    	at a.g.e(Unknown Source:31)
                                                                                                    	at com.ym.library.base.BaseEmulatorActivity.a(Unknown Source:11)
                                                                                                    	at com.ym.library.base.c.c(Unknown Source:295)
                                                                                                    	at com.ym.library.base.BaseEmulatorActivity.a(Unknown Source:2)
                                                                                                    	at c.d$d.a(Unknown Source:6)
                                                                                                    	at com.ym.library.ui.multitouchbutton.MultitouchImageButton.a(Unknown Source:8)
